### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (2032,1348) (1348,2032)

### ISSUE THREAD

**Issue by fxy2012** [Holmes-Alan/ABPN#1]
Dear author,
I ran the code "python main_4x.py"  successfully, but when I ran "eval_4x.py", error occured.  I cannot find the reason of this problem. Could you please help me solve this problem?

**Comment by fxy2012** [comment]
Traceback (most recent call last):
  File "eval_4x.py", line 177, in <module>
    eval()
  File "eval_4x.py", line 99, in eval
    psnr_predicted = PSNR(prediction_Y, GT_Y, shave_border=opt.upscale_factor)
  File "eval_4x.py", line 137, in PSNR
    imdff = pred - gt
ValueError: operands could not be broadcast together with shapes (2032,1348) (1348,2032)
